# Generated by Django 4.2.8 on 2023-12-19 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='Date',
            field=models.DateField(default='1999-12-23'),
            preserve_default=False,
        ),
    ]
